In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 挑戰題一_Bubble Sort
Geoffrey是個喜歡自動化的老師，某次期中考過後，他想要把學生的成績用電腦自動排序，於是他請Andrew幫忙開發這個高難度的程式…

限制：不可以使用Python內建的sort()

提示：

* 每回合都把該回合範圍內最小的數搬到最左邊，最後就可以排好所有的數
* 搬運的方式可以透過兩兩互換

In [19]:
test1 = np.random.randint(1,100,size = 10) # 測試資料

In [20]:
def B_S(arr): # 輸入資料須為array 
    for i in range(len(arr)):
        for j in range(i):
            if(arr[j]>arr[j+1]):
                arr[j+1]=arr[j]
    return(arr)
B_S(test1)

array([49, 49, 49, 54, 54, 54, 96, 96, 96, 99])

# 第一題_算閏年：
請定義一個函式，讀進一個年份，輸出是不是閏年。

提示：
目前使用的格里高利曆閏年規則如下：

* 4的倍數是可能的。
* 100的倍數是不可能的。
* 400的倍數是可能的。

In [27]:
def isLY(year):
    if(year%4==0):
        if(year%100==0):
            if(year%400==0):
                print(f"{year} 是閏年。")
            else:
                print(f"{year} 不是閏年。")
        else:
            print(f"{year} 是閏年。")
    else:
        print(f"{year} 不是閏年。")
isLY(2400)

2400 是閏年。


# 第二題_請實作五乘五矩陣的矩陣加法函式：

In [61]:
m1 = np.random.randint(1,100, size=(5,5))
m2 = np.random.randint(1,100, size=(5,5)) 
print("m1:\n",m1,"\n\nm2:\n",m2)

m1:
 [[39 65 41 65 75]
 [90  2 25 88  5]
 [45 73 14 25 75]
 [64 82 27 57  5]
 [52 99 82  7 96]] 

m2:
 [[ 7 22 72 81 95]
 [16 21 51 32 77]
 [14 56  3 66 27]
 [21 48 98 72  8]
 [36 62 59  9 98]]


In [62]:
def matrix_plus(m1,m2): # m1 m2 需為array
    matrix_p = np.zeros((5,5))
    for i in range(5):
        for j in range(5):
            matrix_p[i][j] = m1[i][j] + m2[i][j]
    return(matrix_p)
matrix_plus(m1,m2)

array([[  46.,   87.,  113.,  146.,  170.],
       [ 106.,   23.,   76.,  120.,   82.],
       [  59.,  129.,   17.,   91.,  102.],
       [  85.,  130.,  125.,  129.,   13.],
       [  88.,  161.,  141.,   16.,  194.]])

# 第三題_錄取分數表格
小明今年考大學
<br/>依照 [國, 英, 數甲, 數乙, 物, 化, 生, 歷, 地, 公]<br/>
<br/>他的分數分別是 [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]<br/>
<br/>而他所想申請的大學各系採計的科目權重分別是<br/>
<br/>{<br/>
<br/>"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],<br/>
<br/>"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],<br/>
<br/>"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],<br/>
<br/>"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],<br/>
<br/>"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],<br/>
<br/>"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],<br/>
<br/>"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],<br/>
<br/>"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],<br/>
<br/>"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]<br/>
<br/>} <br/>


<br/>請幫他做出一個表格<br/>
<br/>第一欄顯示科系<br/>
<br/>接下來顯示權重 並標示科目<br/>
<br/>最後一欄顯示加權分數<br/>

In [120]:
小明的分數= [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
科系加權={
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
}

for i in 科系加權:
    科系加權[i].append(np.dot(np.array(科系加權[i]),np.array(小明的分數)))

columns = ["國文", "英文", "數甲", "數乙", "物理"
         , "化學", "生物", "歷史", "地理", "公民","加權分數"]

df = pd.DataFrame.from_dict(科系加權,orient='index')
df.columns = columns
df

國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075